export const pricingPlans = [
    {
        id: "free",
        title: "Free plan",
        priceMonthly: 10,
        priceYearly: 400,
        users: 1,
        features: [
            "Access to all basic features",
            "Basic reporting and analytics",
            "Up to 10 individual users",
            "200GB individual data each user",
            "Basic chat and email support",
        ],
        active: true,
    },
    {
        id: "pro",
        title: "Pro plan",
        priceMonthly: 20,
        priceYearly: 600,
        users: 2,
        features: [
            "Flexible Plans",
            "Scalability",
            "24/7 Email Support",
            "200 Recordings",
            "30 Days Backup",
        ],
        highlighted: true,
    },
    {
        id: "agent",
        title: "Agent plan",
        priceMonthly: 40,
        priceYearly: 800,
        users: 10,
        features: [
            "Access to all basic features",
            "Basic reporting and analytics",
            "Up to 10 individual users",
            "200GB individual data each user",
            "Basic chat and email support",
        ],
    },
];